# Generated by Django 2.2.1 on 2019-07-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=45)),
                ('under', models.CharField(max_length=45)),
                ('hod', models.CharField(max_length=45)),
            ],
        ),
    ]
