# Generated by Django 2.2.2 on 2019-08-01 08:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval_Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_name', models.CharField(max_length=45)),
                ('required', models.BooleanField()),
                ('first_approval', models.CharField(max_length=45)),
                ('second_approval', models.CharField(max_length=45)),
                ('third_approval', models.CharField(max_length=45)),
                ('fourth_approval', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
                ('holiday_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Leave_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=45)),
                ('leave_days', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('no_of_days', models.IntegerField(default=1)),
                ('supervisor', models.CharField(default='', max_length=45)),
                ('sup_Status', models.CharField(default='Pending', max_length=15)),
                ('hod', models.CharField(default='', max_length=45)),
                ('hod_status', models.CharField(default='Pending', max_length=15)),
                ('hr', models.CharField(default='', max_length=45)),
                ('hr_status', models.CharField(default='Pending', max_length=15)),
                ('app_status', models.CharField(default='Pending', max_length=10)),
                ('remarks', models.TextField()),
                ('balance', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.Leave_Types')),
            ],
        ),
    ]
