# Generated by Django 2.2.1 on 2019-12-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='sup_Status',
            new_name='supervisor_status',
        ),
    ]
