# Generated by Django 3.0 on 2020-02-10 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_details', '0001_initial'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation_details.Department'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation_details.Team'),
        ),
    ]
