# Generated by Django 2.2.1 on 2019-07-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='no_of_days',
            field=models.IntegerField(default=1),
        ),
    ]
