# Generated by Django 3.0.6 on 2020-06-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holidays',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='hod_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='hr_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='supervisor_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
