# Generated by Django 2.2.1 on 2019-08-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_annual_planner'),
    ]

    operations = [
        migrations.AddField(
            model_name='annual_planner',
            name='leave',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leave.Leave_Types'),
        ),
    ]
