# Generated by Django 3.0.6 on 2020-06-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20200605_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='hod_comment',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='hr_comment',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='remarks',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='supervisor_comment',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
