# Generated by Django 2.2.1 on 2019-12-23 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20191223_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod', to='employees.Employee'),
        ),
    ]
