# Generated by Django 2.2.1 on 2019-07-29 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20190729_1025'),
        ('leave', '0003_leaveapplication_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='Employee_Name',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
