# Generated by Django 2.2.1 on 2019-07-23 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaveapplication_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='Employee_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
