# Generated by Django 2.2.1 on 2019-09-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_annual_planner_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='annual_planner',
            name='leave_month',
            field=models.CharField(default='Jan', max_length=4),
        ),
        migrations.AddField(
            model_name='annual_planner',
            name='no_of_days',
            field=models.IntegerField(default=0),
        ),
    ]
