# Generated by Django 2.2.2 on 2019-07-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_bank_account'),
        ('leave', '0003_leaveapplication_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='Employee_Name',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='employee',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
