# Generated by Django 2.2.1 on 2019-07-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20190723_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='Employee_Name',
            new_name='employee',
        ),
    ]
