# Generated by Django 2.2.1 on 2019-12-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20191223_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Supervisor', to='employees.Employee'),
        ),
    ]
