# Generated by Django 2.2.1 on 2019-07-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20190708_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval_Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_name', models.CharField(max_length=45)),
                ('required', models.BooleanField()),
                ('first_approval', models.CharField(max_length=45)),
                ('second_approval', models.CharField(max_length=45)),
                ('third_approval', models.CharField(max_length=45)),
                ('fourth_approval', models.CharField(max_length=45)),
            ],
        ),
    ]
