# Generated by Django 2.2.1 on 2020-01-06 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20200105_1358'),
        ('leave', '0005_auto_20191230_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_year', models.IntegerField()),
                ('entitlement', models.IntegerField()),
                ('residue', models.IntegerField()),
                ('leave_applied', models.IntegerField()),
                ('total_taken', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
    ]
