# Generated by Django 2.2.1 on 2019-07-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_approval_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=60)),
                ('designation', models.CharField(max_length=20)),
                ('nin', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=15)),
                ('apply_date', models.DateField()),
                ('_year', models.CharField(max_length=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('supervisor', models.CharField(max_length=45)),
                ('sup_Status', models.CharField(max_length=15)),
                ('hod', models.CharField(max_length=45)),
                ('hod_status', models.CharField(max_length=15)),
            ],
        ),
    ]
