# Generated by Django 2.2.2 on 2019-07-25 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_auto_20190725_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
