# Generated by Django 2.2.1 on 2019-07-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_auto_20190723_1119'),
        ('leave', '0006_auto_20190725_1241'),
    ]

    operations = [
    ]
