# Generated by Django 2.2.1 on 2020-01-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leave_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_records',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leave_records',
            name='entitlement',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='leave_records',
            name='leave_applied',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leave_records',
            name='residue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leave_records',
            name='total_taken',
            field=models.IntegerField(default=0),
        ),
    ]
