# Generated by Django 2.2.1 on 2019-07-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leave_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave_Application',
        ),
    ]
