# Generated by Django 2.2.1 on 2019-07-15 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_delete_leave_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=60)),
                ('apply_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('supervisor', models.CharField(default='', max_length=45)),
                ('sup_Status', models.CharField(default='', max_length=15)),
                ('hod', models.CharField(default='', max_length=45)),
                ('hod_status', models.CharField(default='', max_length=15)),
                ('hr', models.CharField(default='', max_length=45)),
                ('hr_status', models.CharField(default='', max_length=15)),
                ('app_status', models.CharField(default='', max_length=10)),
                ('remarks', models.TextField()),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.Leave_Types')),
            ],
        ),
    ]
