# Generated by Django 2.0.13 on 2019-06-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('marital_status', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=20)),
                ('nssf_no', models.CharField(max_length=20)),
                ('telephone_no', models.CharField(max_length=20)),
                ('residence_address', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=20)),
                ('ura_tin', models.CharField(max_length=20)),
                ('image_url', models.CharField(max_length=20)),
            ],
        ),
    ]
