# Generated by Django 3.0 on 2020-01-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='job_type',
            new_name='type',
        ),
    ]
