# Generated by Django 2.0.13 on 2019-06-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='', max_length=30),
        ),
    ]
