# Generated by Django 3.0 on 2020-01-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200111_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='currency',
            new_name='salary_currency',
        ),
    ]
