# Generated by Django 2.2.1 on 2019-07-31 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20190731_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='team',
        ),
    ]
