# Generated by Django 2.2.2 on 2019-08-29 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('employees', '0002_auto_20190829_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowance',
            name='currency',
        ),
        migrations.AddField(
            model_name='employee',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='settings.Currency'),
        ),
    ]
