# Generated by Django 2.2.1 on 2019-06-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_position'),
        ('employees', '0002_leave'),
    ]

    operations = [
    ]
