# Generated by Django 2.2.1 on 2019-11-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='balance_last_year',
            field=models.IntegerField(default=0),
        ),
    ]
