# Generated by Django 2.0.13 on 2019-06-24 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_merge_20190618_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAddress',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employees.Employee')),
                ('district', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('sub_county', models.CharField(max_length=20)),
                ('parish', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='image_url',
            field=models.CharField(default='', max_length=20),
        ),
    ]
