# Generated by Django 2.2.2 on 2019-07-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_bankdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bank_account',
        ),
    ]
