# Generated by Django 2.2.2 on 2019-08-29 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20190829_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='currency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Currency'),
        ),
    ]
