# Generated by Django 2.2.1 on 2020-01-05 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20200105_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='supervisors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
