# Generated by Django 3.0 on 2020-01-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20200111_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='salary_currency',
            new_name='currency',
        ),
    ]
