# Generated by Django 2.2.1 on 2019-07-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_status',
            field=models.CharField(default='At Work', max_length=45),
        ),
    ]
