# Generated by Django 2.2.1 on 2019-11-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_balance_last_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='annual_allowance',
            field=models.IntegerField(default=21),
        ),
    ]
