# Generated by Django 2.2.2 on 2019-08-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20190829_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='currency',
        ),
    ]
