# Generated by Django 3.0 on 2020-01-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20200113_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='lunch_allowance',
            field=models.IntegerField(default=0),
        ),
    ]
