# Generated by Django 2.0.13 on 2019-06-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
