# Generated by Django 2.2.2 on 2019-07-29 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20190727_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationdetail',
            name='department',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.Departments'),
        ),
    ]
