# Generated by Django 3.0 on 2020-02-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20200127_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationdetail',
            name='department',
        ),
        migrations.RemoveField(
            model_name='organisationdetail',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='organisationdetail',
            name='position',
        ),
        migrations.RemoveField(
            model_name='organisationdetail',
            name='team',
        ),
        migrations.RemoveField(
            model_name='position',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='team',
            name='department',
        ),
        migrations.RemoveField(
            model_name='team',
            name='supervisors',
        ),
    ]
