# Generated by Django 2.2.1 on 2019-07-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20190729_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='leave_balance',
            field=models.IntegerField(default=21),
        ),
    ]
