# Generated by Django 2.2.1 on 2019-11-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_annual_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default='', max_length=45),
        ),
    ]
