# Generated by Django 2.0.13 on 2019-06-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20190625_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='institution',
            field=models.CharField(max_length=100),
        ),
    ]
