# Generated by Django 3.0 on 2020-02-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20200210_1218'),
        ('leave', '0002_auto_20200210_1218'),
        ('contracts', '0004_auto_20200210_1218'),
        ('learning_and_development', '0004_auto_20200210_1218'),
        ('recruitment', '0005_auto_20200210_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='OrganisationDetail',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
