# Generated by Django 2.2.2 on 2019-08-29 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('employees', '0006_auto_20190829_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='currency',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='settings.Currency'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='workstation',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
