# Generated by Django 2.2.2 on 2019-07-29 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20190729_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationdetail',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Departments'),
        ),
        migrations.AlterField(
            model_name='organisationdetail',
            name='position',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Job_Titles'),
        ),
    ]
