# Generated by Django 2.2.2 on 2019-08-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20190829_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
