# Generated by Django 2.0.13 on 2019-06-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_emergencycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('relationship', models.CharField(max_length=40)),
                ('mobile_number', models.CharField(max_length=40)),
                ('percentage', models.CharField(max_length=40)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
