# Generated by Django 2.2.2 on 2019-08-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20190829_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_station',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
