# Generated by Django 2.0.13 on 2019-06-29 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20190628_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('national_id', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('occupation', models.CharField(max_length=40)),
                ('telephone', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=40)),
                ('passport_number', models.CharField(max_length=40)),
                ('alien_certificate_number', models.CharField(max_length=40)),
                ('immigration_file_number', models.CharField(max_length=40)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
    ]
