# Generated by Django 2.2.2 on 2019-09-09 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='employees.Employee')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisees', to='employees.Employee')),
            ],
        ),
    ]
