# Generated by Django 2.2.2 on 2019-07-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_dependant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependant',
            name='gender',
            field=models.CharField(default='', max_length=40),
        ),
    ]
