# Generated by Django 2.2.2 on 2019-07-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_dependant_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(default='', max_length=30),
        ),
    ]
