# Generated by Django 2.2.2 on 2019-07-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.CharField(default='', max_length=3),
        ),
    ]
