# Generated by Django 2.2.1 on 2019-07-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=45)),
                ('hod', models.CharField(max_length=45)),
                ('teams', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
