# Generated by Django 2.2.2 on 2019-07-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.CharField(default='', max_length=20),
        ),
    ]
