# Generated by Django 2.2.1 on 2019-07-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_auto_20190710_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='n_teams',
            field=models.IntegerField(default=0),
        ),
    ]
