# Generated by Django 2.2.1 on 2019-07-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_auto_20190710_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='n_teams',
        ),
    ]
