# Generated by Django 2.2.1 on 2019-07-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_auto_20190711_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='jst',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=30),
        ),
    ]
