# Generated by Django 3.0 on 2020-01-11 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=20)),
                ('vacancy', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('post_date', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('show_salary', models.BooleanField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='employees.Position')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='employees.Employee')),
                ('job_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.JobAdvertisement')),
            ],
        ),
    ]
