# Generated by Django 3.0 on 2020-01-16 05:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvertisement',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2020, 1, 16, 5, 29, 11, 324847, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
