# Generated by Django 3.0 on 2020-01-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_jobadvertisement_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvertisement',
            name='show_salary',
            field=models.BooleanField(default=True),
        ),
    ]
