# Generated by Django 2.2.1 on 2020-02-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20200116_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv',
            field=models.FileField(upload_to='cvs/'),
        ),
    ]
