# Generated by Django 2.2.2 on 2020-03-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_auto_20200210_1218'),
        ('recruitment', '0004_auto_20200203_1244'),
    ]

    operations = [
    ]
