# Generated by Django 3.0 on 2020-02-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_admin', '0004_auto_20200217_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audittrail',
            old_name='created',
            new_name='created_time',
        ),
    ]
