# Generated by Django 3.0 on 2020-02-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_admin', '0006_auto_20200217_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audittrail',
            old_name='created_time',
            new_name='created_at',
        ),
    ]
