# Generated by Django 3.0 on 2020-01-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='Risk',
            new_name='risk',
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
