# Generated by Django 2.2.2 on 2019-09-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('supervisor_approval', models.CharField(default='Pending', max_length=10)),
                ('HOD_approval', models.CharField(default='Pending', max_length=10)),
                ('HR_approval', models.CharField(default='Pending', max_length=10)),
                ('cfo_approval', models.CharField(default='Pending', max_length=10)),
                ('ceo_approval', models.CharField(default='Pending', max_length=10)),
                ('supervisee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='employees.Employee')),
                ('supervisor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisee', to='employees.Employee')),
            ],
        ),
    ]
