# Generated by Django 3.0 on 2019-12-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimeapplication',
            name='supervisor',
        ),
        migrations.AlterField(
            model_name='overtimeapplication',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
