# Generated by Django 2.2.2 on 2019-09-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_auto_20190817_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtimeapplication',
            old_name='applicant',
            new_name='supervisee',
        ),
        migrations.AddField(
            model_name='overtimeapplication',
            name='ceo_approval',
            field=models.CharField(default='False', max_length=10),
        ),
        migrations.AddField(
            model_name='overtimeapplication',
            name='cfo_approval',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
