# Generated by Django 2.2.2 on 2019-09-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_auto_20190929_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimeapplication',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='overtimeapplication',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
