# Generated by Django 2.2.1 on 2019-12-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='UGX', max_length=10, unique=True)),
                ('desc', models.CharField(default='Ugandan Shillings', max_length=20)),
                ('cost', models.CharField(default='1', max_length=20)),
            ],
        ),
    ]
