# Generated by Django 2.2.1 on 2019-08-05 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_team'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solitonuser',
            name='soliton_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.Departments'),
        ),
        migrations.AddField(
            model_name='solitonuser',
            name='soliton_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.Teams'),
        ),
    ]
