# Generated by Django 2.2.1 on 2019-12-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='number',
        ),
    ]
