# Generated by Django 2.2.2 on 2019-09-04 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_auto_20190904_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solitonuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
