# Generated by Django 2.2.2 on 2019-07-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='unread', max_length=10),
        ),
    ]
