# Generated by Django 2.2.2 on 2019-09-04 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_auto_20190904_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solitonuser',
            name='soliton_role',
        ),
        migrations.AddField(
            model_name='solitonuser',
            name='is_ceo',
            field=models.CharField(default='False', max_length=10),
        ),
        migrations.AddField(
            model_name='solitonuser',
            name='is_cfo',
            field=models.CharField(default='False', max_length=10),
        ),
        migrations.AddField(
            model_name='solitonuser',
            name='is_hod',
            field=models.CharField(default='False', max_length=10),
        ),
        migrations.AddField(
            model_name='solitonuser',
            name='is_hr',
            field=models.CharField(default='False', max_length=10),
        ),
        migrations.AlterField(
            model_name='solitonuser',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='solitonuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
