# Generated by Django 2.2.2 on 2019-09-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_auto_20190904_0858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolitonRole',
        ),
    ]
