# Generated by Django 2.2.2 on 2019-09-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0005_delete_solitonrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solitonuser',
            name='employee',
        ),
    ]
