# Generated by Django 2.2.2 on 2019-09-04 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_title'),
        ('role', '0006_remove_solitonuser_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='solitonuser',
            name='employee',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
