# Generated by Django 3.0 on 2020-01-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('producer', models.CharField(max_length=40)),
                ('format', models.CharField(max_length=10)),
                ('year_published', models.IntegerField()),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='resources')),
            ],
        ),
    ]
