# Generated by Django 3.0 on 2020-01-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20200127_1626'),
        ('learning_and_development', '0002_auto_20200130_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='department',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
