# Generated by Django 3.0.7 on 2020-06-11 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_nssf', models.FloatField()),
                ('employer_nssf', models.FloatField()),
                ('gross_salary', models.FloatField()),
                ('net_salary', models.FloatField()),
                ('paye', models.FloatField()),
                ('total_nssf_contrib', models.FloatField(default=0)),
                ('overtime', models.FloatField()),
                ('bonus', models.FloatField(default=0)),
                ('sacco_deduction', models.FloatField()),
                ('damage_deduction', models.FloatField()),
                ('prorate', models.CharField(default='0.0', max_length=20)),
                ('currency', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='settings.Currency')),
                ('employee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
                ('payroll_record', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='payroll.PayrollRecord')),
            ],
        ),
    ]
