# Generated by Django 2.2.1 on 2019-12-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_nssf', models.IntegerField()),
                ('employer_nssf', models.IntegerField()),
                ('gross_salary', models.IntegerField()),
                ('net_salary', models.IntegerField()),
                ('paye', models.IntegerField()),
                ('total_nssf_contrib', models.IntegerField(default=0)),
                ('overtime', models.IntegerField()),
                ('bonus', models.IntegerField(default=0)),
                ('sacco_deduction', models.IntegerField()),
                ('damage_deduction', models.IntegerField()),
                ('prorate', models.CharField(default='0.0', max_length=20)),
                ('lunch_allowance', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
                ('payroll_record', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='payroll.PayrollRecord')),
            ],
        ),
    ]
