# Generated by Django 2.2.1 on 2019-07-31 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_auto_20190731_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_nssf', models.CharField(max_length=15)),
                ('employer_nssf', models.CharField(max_length=15)),
                ('gross_salary', models.CharField(default='', max_length=15)),
                ('net_salary', models.CharField(default='', max_length=15)),
                ('paye', models.CharField(max_length=20)),
                ('total_nssf_contrib', models.CharField(default='', max_length=20)),
                ('total_statutory', models.CharField(default='', max_length=20)),
                ('overtime', models.CharField(default='0.0', max_length=20)),
                ('bonus', models.CharField(default='0.0', max_length=20)),
                ('sacco_deduction', models.CharField(default='0.0', max_length=20)),
                ('damage_deduction', models.CharField(default='0.0', max_length=20)),
                ('prorate', models.CharField(default='0.0', max_length=20)),
                ('employee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
                ('payroll_record', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='payroll.PayrollRecord')),
            ],
        ),
    ]
