# Generated by Django 2.2.2 on 2019-09-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payroll',
            new_name='Payslip',
        ),
    ]
