# Generated by Django 3.0.6 on 2020-06-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='damage_deduction',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employee_nssf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employer_nssf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='gross_salary',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='net_salary',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='overtime',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='paye',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='sacco_deduction',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='total_nssf_contrib',
            field=models.FloatField(default=0),
        ),
    ]
