# Generated by Django 3.0 on 2020-01-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='lunch_allowance',
        ),
    ]
