# Generated by Django 3.0 on 2020-06-08 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='currency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='settings.Currency'),
        ),
    ]
