# Generated by Django 2.2.2 on 2019-07-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_grade'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='employee',
        ),
        migrations.AddField(
            model_name='payroll',
            name='employees',
            field=models.ManyToManyField(to='employees.Employee'),
        ),
    ]
