# Generated by Django 2.2.2 on 2019-07-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20190708_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='total_nssf_contrib',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_statutory',
            field=models.CharField(default='', max_length=20),
        ),
    ]
