# Generated by Django 2.2.2 on 2019-07-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_grade'),
        ('payroll', '0002_auto_20190705_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='employees',
        ),
        migrations.AddField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
