# Generated by Django 3.0.7 on 2020-06-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20200613_2047'),
        ('payroll', '0002_auto_20200608_1013'),
    ]

    operations = [
    ]
