# Generated by Django 2.2.2 on 2019-09-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20190929_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='total_nssf_contrib',
            field=models.IntegerField(default=0),
        ),
    ]
