# Generated by Django 2.2.2 on 2019-07-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20190705_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='basic_pay',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='gross_pay',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='net_pay',
        ),
        migrations.AddField(
            model_name='payroll',
            name='gross_salary',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='payroll',
            name='net_salary',
            field=models.CharField(default='', max_length=15),
        ),
    ]
