# Generated by Django 2.2.2 on 2019-07-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20190708_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='bonus',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='damage_deduction',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='prorate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='sacco_deduction',
            field=models.CharField(default='', max_length=20),
        ),
    ]
