# Generated by Django 2.2.2 on 2019-09-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payslip_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='lunch_allowance',
            field=models.IntegerField(default=0),
        ),
    ]
