# Generated by Django 2.2.7 on 2019-11-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_ceo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_cfo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_hr',
            field=models.BooleanField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
