# Generated by Django 3.0 on 2019-12-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
