# Generated by Django 2.2.1 on 2020-01-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addd',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
