# Generated by Django 2.2.1 on 2020-01-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_auth', '0002_auto_20200108_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='addd',
        ),
    ]
