# Generated by Django 3.0.6 on 2020-07-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
