# Generated by Django 3.0 on 2020-05-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_details', '0002_auto_20200320_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='supervisors',
            new_name='supervisor',
        ),
    ]
