# Generated by Django 3.0 on 2020-02-03 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_auto_20200127_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=40)),
                ('institution', models.CharField(max_length=40)),
                ('duration', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('business_case', models.TextField()),
                ('objectives', models.TextField()),
                ('preparations', models.TextField()),
                ('skills', models.CharField(max_length=40)),
                ('knowledge', models.TextField()),
                ('comments', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
    ]
