# Generated by Django 3.0 on 2020-02-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_training_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='business_case',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='knowledge',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='preparations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='skills',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
