# Generated by Django 3.0 on 2020-02-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_training_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('purpose', models.TextField(blank=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
