# Generated by Django 3.0 on 2020-02-05 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_training_schedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Training_Schedule',
            new_name='TrainingSchedule',
        ),
    ]
