# Generated by Django 3.0 on 2020-02-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20200205_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingschedule',
            name='venue',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
